version: '3'

services:
  mysql_db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
  
  webapp:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8888:8080"
    tty: true
    restart: always
    depends_on:
      - mysql_db
    environment:
      - RELSTORAGE_HOST=mysql_db
      - RELSTORAGE_DB=plone
      - RELSTORAGE_USER=root
      - RELSTORAGE_PASS=root
      - DSN_SENTRY=""
      